### ISSUE TITLE
Display Content or Message for Blank Page with No Negations (Improvement) (See Description)

### ISSUE THREAD

**Issue by Bikatr7** [network-goods-institute/negation-game#53]
### **Description**
When navigating to home (/) with no points/negations in the database, the page is entirely blank. This may create confusion for users, even though such instances are expected to be rare in production.

### **Steps to Reproduce**
1. Have a fresh local build with no database or a blank one
2. Ensure the page has no points/negations (e.g., a new or empty topic).
3. Observe the page:
   - Notice that it displays as entirely blank without any UI elements or messaging aside from sign in, make point, and title.

### **Expected Behavior**
The page should provide some context or messaging to the user when no negations are present. For example:
- A placeholder message like "No points/negations found. Be the first to contribute!" 
- A visual indicator or call-to-action encouraging users to add content.

### **Actual Behavior**
- The page remains completely blank when no negations are present, offering minimal feedback or options to the user.

### **Reproducibility**
- Occurs consistently on pages with no negations.

### **Environment**
- **Platform:** Windows, Firefox
- **Build:** https://github.com/network-goods-institute/negation-game/commit/195cdac04b2aea52c35c6b1b77a8e91c64b5202c

**Comment by volkyeth** [comment]
forgot to close on e78d870c56f3de8d9c02ae89557743c582b0f391
